repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-ast

  - repo: local
    hooks:
      - id: check-poetry
        name: Check validity of `pyproject.toml` file
        language: system
        entry: poetry check
        pass_filenames: false
        always_run: true
      - id: lint
        name: Lint Python files
        language: system
        entry: poetry run inv lint
        pass_filenames: false
        always_run: true
      - id: quick-tests
        name: Runs quick tests
        language: system
        entry: poetry run inv quick-test
        pass_filenames: false
        always_run: true
