language: python
cache:
  pip: true
  directories:
    - .hypothesis

python:
  - 3.7
  - 3.6
env:
  - HYPOTHESIS_MAX_EXAMPLES=100
  - HYPOTHESIS_MAX_EXAMPLES=100_000

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - inv lint
  - travis_wait inv test
