import:
  - source: neimad/travis-python:dev.yml
    mode: deep_merge_prepend

env:
  matrix:
    - PYTHON="3.8"
    - PYTHON="3.7"
    - PYTHON="3.6"
  global:
    - CACHE=$HOME/cache
    - PYENV_ROOT=$CACHE/pyenv
    - PIP_CACHE_DIR=$CACHE/pip
    - VENVS_DIR=$CACHE/virtualenvs
    - PRE_COMMIT_HOME=$CACHE/pre-commit
    - HYPOTHESIS_STORAGE_DIRECTORY=$CACHE/hypothesis

before_install:
  # Upgrade Pip
  - python -m pip install -U pip
  # Install Poetry
  - pip install poetry
  - poetry config virtualenvs.path "$VENVS_DIR"

install:
  - poetry install
  - poetry debug:info

script:
  - poetry run pre-commit run -a
  - travis_wait poetry run pytest

cache:
  directories:
    - $CACHE

before_cache:
  - poetry run pre-commit gc
